project:
  type: website
  output-dir: docs

website:
  title: "Joseph Mullins"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true



